image: satantime/puppeteer-node

stages:
  - if-UI-acceptance-tests

if-UI-acceptance-tests:
    stage: if-UI-acceptance-tests
    script:
      - yarn install
      - npx cucumber-js --format progress
